// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcivAjtqnWP3d-ZhuexMzg5yKagEYaZeM',
    appId: '1:676499970622:web:7589e66ff85fcf0fe14f6f',
    messagingSenderId: '676499970622',
    projectId: 'esh7enly-cf37d',
    authDomain: 'esh7enly-cf37d.firebaseapp.com',
    storageBucket: 'esh7enly-cf37d.firebasestorage.app',
    measurementId: 'G-TCKTS7FRB0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpJ1R2rQ8SmWN3iShx2TvEWYurndJ5p5U',
    appId: '1:676499970622:android:14481e39fdd04af2e14f6f',
    messagingSenderId: '676499970622',
    projectId: 'esh7enly-cf37d',
    storageBucket: 'esh7enly-cf37d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNf2s7j9eTCygZoGA29lIWNdldRHl2XXQ',
    appId: '1:676499970622:ios:0fc9379c909aa419e14f6f',
    messagingSenderId: '676499970622',
    projectId: 'esh7enly-cf37d',
    storageBucket: 'esh7enly-cf37d.firebasestorage.app',
    iosClientId: '676499970622-5lae552g6b7al8e4eb6r6pbi8qep6j8c.apps.googleusercontent.com',
    iosBundleId: 'com.example.esh7enlyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcivAjtqnWP3d-ZhuexMzg5yKagEYaZeM',
    appId: '1:676499970622:web:b0a77e931f7d68bde14f6f',
    messagingSenderId: '676499970622',
    projectId: 'esh7enly-cf37d',
    authDomain: 'esh7enly-cf37d.firebaseapp.com',
    storageBucket: 'esh7enly-cf37d.firebasestorage.app',
    measurementId: 'G-0CS31M8H7T',
  );
}
